apiVersion: apps/v1
kind: Deployment
metadata:
  name: aave-swarm-agents
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aave-swarm
  template:
    metadata:
      labels:
        app: aave-swarm
    spec:
      containers:
      - name: swarm-agents
        image: northamerica-northeast2-docker.pkg.dev/aave-swarm-v6-2/swarm-agents/swarm-agents:latest
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            cpu: "2"
            memory: "8Gi"
            nvidia.com/gpu: 1
        envFrom:
        - configMapRef:
            name: swarm-config
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-spot: "true"
